name: Build executable mac
on:
  push:
    branches: [feature/**, fix/**, development]
  pull_request:
    branches: [development]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install TA-lib
        run: brew install ta-lib
      - name: save pip cache dir
        id: pipdir
        run: echo "::set-output name=pipcachedir::$(pip cache dir)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.pipdir.outputs.pipcachedir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements-ci.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: install requirements
        run: pip install -r requirements-ci.txt
      - name: build executable
        run: python build_scripts/build_windows.py
      - name: set executable bit
        run: chmod +x ./dist/engine
      - name: init
        run: ./dist/engine init new-dir
      - name: Archive built executable
        uses: actions/upload-artifact@v2
        with:
          name: macos-exe
          path: dist/engine
  test:
    needs:
      - build
    runs-on: macos-latest
    steps:
      - name: exe
        uses: actions/download-artifact@v2
        with:
          name: macos-exe
      - name: talib
        run: brew install ta-lib
      - name: list contents
        run: ls
      - name: set executable bit
        run: chmod +x ./engine
      - name: init
        run: ./engine init new-dir
      - name: run
        run: ../engine
        working-directory: ./new-dir
