# Triggers the Github Workflow to increase the version numher and publish an update to the Github Package.

name: DockerHub Deployment

on:
  push:
    branches:
    - development

jobs:
  publish_package:
    runs-on: ubuntu-latest
    needs: generate-new-tag
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: dematrading/engine:develop
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
