name: Test PR/Push
on:
  push:
    branches: [feature/**, fix/**, development]
  pull_request:
    branches: [development]
   
jobs:
  pytest-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install pytest-cov
      - run: pip install pytest
      - run: pytest
      
      - name: Run codacy-coverage-reporter
      - run: pytest --cov-report xml
      - uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: cobertura.xml
      
