name: Test PR/Push
on:
  pull_request:
    branches: [development, main]
jobs:
  pytest-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Pytest and create a coverage report
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: |
          pip install pytest-cov
          pip install -r requirements-ci.txt
          pytest --cov-report xml:cobertura.xml --cov=.

      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: cobertura.xml
      
